config/routes.rb
Rails.application.routes.draw do  

  root 'welcome#index'
  get 'welcome/index'

  resources :users, only: [:new, :create, :show]

  resources :restaurants do
  	resources :reservations
	end

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :party_size, :date, :time, presence: true

  validate :availability

  private
  def availability
    if !restaurant.available?(party_size, date, time)
      errors.add(:base, "Restaurant is full for this spot")
    end
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :user # restaurant is owned by a user

  def available?(party_size, date, time)
		total_reservation_count = reservations.where(date: date, time: time).sum(:party_size)
		party_size + total_reservation_count <= 100 #capacity
	end

  def self.search(search)
    if search
      where("LOWER(name) LIKE ? OR LOWER(category) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
    else
      self.all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :reservations
  has_many :restaurants #if an owner and added a restaurant
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please Log In!"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :ensure_logged_in, only: [:create, :destroy]
	before_filter :load_restaurant

  def show
    @reservation = Reservation.find(params[:id])
  end

	def new
    @reservation = Reservation.new
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)
  	@reservation.user = current_user
		if @reservation.save
  		redirect_to restaurant_path(params[:restaurant_id]), notice: "Your reservation has been booked!"
  	else
  		flash[:alert] = @reservation.errors.full_messages.to_sentence
  		redirect_to new_restaurant_reservation_path(@restaurant, @reservation)
      # render :new
  	end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = @reservation.errors.full_messages.to_sentence
      redirect_to edit_restaurant_reservation_path(@restaurant, @reservation)
      # render :edit
    end
  end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		redirect_to restaurant_path, notice: "Your reservation has been cancelled."
	end

 private
  def reservation_params
  	params.require(:reservation).permit(:party_size, :date, :time)
  end

  def load_restaurant
  	@restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    # @restaurants = Restaurant.all
  	@restaurants = Restaurant.search(params[:search])
  end


  def show
  	@restaurant = Restaurant.find(params[:id])
    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
  	@restaurant = Restaurant.new
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)

  	if @restaurant.save
  		redirect_to restaurants_url(@restaurant)

  	else
  		render :new
  	end
  end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update_attributes(restaurant_params)
			redirect_to restaurant_path(@restaurant)
		else
			render :edit
		end
	end
	
	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_path
	end

  private
  def restaurant_params
  	params.require(:restaurant).permit(:name, :description, :address, :phone_number, :category, :capacity)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry for debugging lines of code
    if @user.save
      redirect_to restaurants_url, notice:"Signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    # @reservations = Reservation.find(params[@user.id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Seat Yourself</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_url %></li>
        <li><%= link_to "Restaurants", restaurants_path %></li>
        <li><%= link_to "Add Restaurant", new_restaurant_url %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "My Reservations", user_path(current_user) %></li>
            <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", new_session_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      <% end  %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Seat Yourself</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_maps_api}" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navigation' %>

      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |r| %> 
	<div class="field">
		<%= r.label :party_size %> <br>
		<%= r.number_field :party_size %> <br>
	</div>
	<div class="field">
		<%= r.label :date %> <br>
		<%= r.date_field :date %> <br>
	</div>
	<div class="field">
		<%= r.label :time %> <br>
		<%= r.time_field :time, type: 'time', step: "#{60.minutes}" %> <br>
	</div>
	<div class="action">
		<%= r.submit %>
	</div>

	<% end %>

app/views/reservations/edit.html.erb
<h1>Edit your Reservation at <%= @restaurant.name %></h1>

<% if current_user %>
    <%= render 'reservations/form' %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p>
<% end %>

<br>

<div>
  <%= link_to "Back to #{@restaurant.name}", restaurant_path(@restaurant) %>  
</div>

app/views/reservations/new.html.erb
<h1>Book a Reservation</h1>

<% if current_user %>
  <h4>New Reservation</h4>
    <%= render 'reservations/form' %>
  <% else %>
  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p>
<% end %>

<br>

<div>
  <%= link_to "Back to #{@restaurant.name}", restaurant_path(@restaurant) %>  
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |r| %> 
	<div class="field">
		<%= r.label :name %> <br>
		<%= r.text_field :name %> <br>
	</div>
	<div class="field">
		<%= r.label :description %> <br>
		<%= r.text_area :description %> <br>
	</div>
	<div class="field">
		<%= r.label :address %> <br>
		<%= r.text_field :address %> <br>
	</div>
	<div class="field">
		<%= r.label :phone_number %> <br>
		<%= r.text_field :phone_number %> <br>
	</div>
	<div class="field">
		<%= r.label :category %> <br>
		<%= select(:restaurant, :category, options_for_select(["Chinese", "Italian", "Fusion"])) %>
 	</div>
	<div class="action">
		<%= r.submit %>
	</div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %> </h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= form_tag restaurants_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @restaurants.each do |restaurant| %>
  <p><%= link_to restaurant.name, restaurant_path(restaurant) %> </p>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>


<%= render 'form' %> 

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %></h1>

<div class="data">
  <%= @restaurant.description%><br>
  <strong>Address:</strong> <%= @restaurant.address%> <br>
  <strong>Phone:</strong> <%= @restaurant.phone_number%><br> 
  <strong>Cuisine:</strong> <%= @restaurant.category%><br>
</div>

<!-- if the user created the restaurant, dispaly the edit and delete options
<%#= if current_user == @restaurant %>
  <p>
    <%#= link_to "Edit", edit_restaurant_path %><br>
    <%#= link_to "Delete Restaurant", @restaurant, method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?"} %>
  </p>
<%# end %> -->

<div id="map-canvas" data-latitude="43.6426" data-longitude="-79.3871"></div>

<h2><%= link_to "Reserve a table", new_restaurant_reservation_path(@restaurant) %></h2>

<div>
  <h3>Currently Booked Reservations</h3>
<!-- why does an empty reservation info show up only when a user is logged in? -->
  <% @restaurant.reservations.each do |reservation| %>
    <p>
      <% if reservation.user != nil %>
        <strong>Booked for:</strong> <%= reservation.user.name %>
      <% end %><br>
      <strong>Party size:</strong> <%= reservation.party_size %><br>
      <strong>Date:</strong> <%= reservation.date %><br>
      <strong>Time:</strong> <%= reservation.time %>
      <br>
      <% if reservation.user == current_user %>
        <%= link_to "Edit" , edit_restaurant_reservation_url(@restaurant, reservation) %>
        <%= link_to "Cancel Reservation", restaurant_reservation_path(@restaurant, reservation), method: :delete, data: {confirm: "Are you sure you want to cancel this reservation?"} %>

      <% end %>
    </p>
  <% end %>
  
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div class="actions"><%= f.submit %></div>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Reservations</h1>

<ul>
  <% @user.reservations.each do |reservation| %>
    <li>
      Reserved at: <%= reservation.restaurant.name %><br>
      Date: <%= reservation.date %><br>
      Time: <%= reservation.time %><br>
      Party of: <%= reservation.party_size %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Seat Yourself</h1>
  <p class="lead">Search Restaurants and make reservations</p>
  <% unless current_user %>
    <p><a class="btn btn-lg btn-success" href="/users/new" role="button">Sign up today</a></p>
    <%#= link_to  %>
  <% end %>
</div>